platform :ios, '9.0'
plugin 'cocoapods-imy-bin'
use_binaries!
#set_use_source_pods ['Masonry']

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
 #  use_frameworks!

  # Pods for Demo
  pod 'AFNetworking', '4.0.1'
  pod 'YYImage/WebP'
  pod 'TMUICore', '2.0.25'
    pod 'TMUIExtensions', '2.0.25'
    pod 'TMUIComponents', '2.0.25'
end
