platform :ios, '9.0'
plugin 'cocoapods-imy-bin'
use_binaries!
#set_use_source_pods ['Masonry']

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
 #  use_frameworks!

  # Pods for Demo
  pod 'TGaiaXiOS', '1.0.0'
end
